version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/nodeapp
hooks:
 AfterInstall:
   - location: scripts/after_install.sh
     runas: root
     timeout: 300
 
 ApplicationStart:
   - location: scripts/application_start.sh
     runas: root
     timeout: 300
